# Generated by Django 5.0.6 on 2024-07-07 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
        ("produtos", "0004_rename_produtos_produto"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Brands",
            new_name="Brand",
        ),
    ]
