# Generated by Django 5.0.6 on 2024-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sku",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("unit", models.CharField(max_length=200, verbose_name="Unidade")),
                (
                    "origin",
                    models.SmallIntegerField(max_length=2, verbose_name="Origem"),
                ),
                ("ncm", models.CharField(max_length=10, verbose_name="NCM")),
                (
                    "cest",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="CEST"
                    ),
                ),
                ("price", models.FloatField(verbose_name="Preço de Venda")),
                (
                    "cost",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Preço de Custo"
                    ),
                ),
                (
                    "net_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso Líquido"
                    ),
                ),
                (
                    "gross_weight",
                    models.FloatField(blank=True, null=True, verbose_name="Peso Bruto"),
                ),
                (
                    "lenght",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Comprimento do produto"
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Largura do produto"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Altura do produto"
                    ),
                ),
                (
                    "expire_day",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Descrição Principal",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Descrição Complementar",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
