# Generated by Django 5.0.6 on 2024-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="origin",
            field=models.SmallIntegerField(verbose_name="Origem"),
        ),
    ]
