# Generated by Django 5.0.6 on 2024-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0002_alter_produtos_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="ean",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                verbose_name="Código de barras EAN",
            ),
        ),
        migrations.AddField(
            model_name="produtos",
            name="stock",
            field=models.FloatField(blank=True, null=True, verbose_name="Estoque"),
        ),
    ]
