# Generated by Django 5.0.6 on 2024-06-07 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0003_produtos_ean_produtos_stock"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produtos",
            new_name="Produto",
        ),
    ]
