# Generated by Django 5.0.6 on 2024-07-07 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0002_rename_brands_brand"),
        ("category", "0001_initial"),
        ("produtos", "0004_rename_produtos_produto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="lenght",
            new_name="length",
        ),
        migrations.AddField(
            model_name="produto",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="brands.brand",
                verbose_name="Marca",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="category.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço de Custo",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço de Venda"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="Estoque"),
        ),
    ]
